#-----------------------------------------------EXERCICIO 6 - CONVENÇÃO DE TIPOS-----------------------------------------------------------------------------------------------------------------------------------------------------------


print(10 / 2)
#>> 5.0 -> divisão sempre retorna float

print(type(10 / 2))
#>> <class 'float'>

print(10 / 3)
#>> 3.3333333333333335

print(10 // 3)
#>> 3 -> retorna um valor inteiro para a divisão, se necessario, truncando.

print(type(10 // 3))
#>> <class 'int'>

print(2 + True)
#>> 3 -> em operações numericas valores boleanos retornam 1 para true e 0 para false

print(2 + False)
#>> 2 -> em operações numericas valores boleanos retornam 1 para true e 0 para false

print(type(1 + 2))
#>> <class 'int'>

print(type(1 + 2.5))
#>> <class 'float'> -> contas de int + float, retorna float por ter mais capacidade.






#-----------------------------------------------FIM DO EXERCICIO 6 - CONVENÇÃO DE TIPOS-----------------------------------------------------------------------------------------------------------------------------------------------------------
